Do not install VM extensions when `var.allow_extension_operations` is `false`
cloudeteer/terraform-azurerm-vm pull request #37
Opened 2024-10-15 12:24 UTC by neonwhiskers

Updated the for_each block to dynamically control extension creation.

2024-10-15 12:38 UTC, rswrz requested changes
Please also add a note to the description of the `extensions` variable about its dependency on the `allow_extension_operations` variable. Make sure it is clear that the list of extension names in the `extensions` variable will be ignored if `allow_extension_operations` is set to `true`.

2024-10-16 09:04 UTC, rswrz requested changes

2024-10-16 09:04 UTC, rswrz commented on variables.tf
> +    Note: The extensions listed here will only be applied if `allow_extension_operations` is set to `true`. If `allow_extension_operations` is set to `false`, this list will be ignored and no extensi
```suggestion
    **NOTE**: The extensions listed here will only be applied if `allow_extension_operations` is set to `true` (default). If `allow_extension_operations` is set to `false`, this list will be ignored and no extensions will be created.
```

2024-10-16 09:14 UTC, rswrz approved these changes

2024-10-22 13:52 UTC, lixhunter approved these changes

2024-10-22 13:57 UTC, merged